mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include,path

import polls

urlpatterns = [
    path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from . import views
app_name ='polls'
urlpatterns = [
    #end:localhost/polls/
    path('', views.IndexView.as_view(), name='index'),
    #end:/polls/5/
    path('<int:pk>/',views.DetailView.as_view(),name='detail'),
    #end:/polls/5/results/
    path('<int:pk>/results/',views.ResultsView.as_view(),name='results'),
    #end:/polls/5/vote/
    path('<int:question_id>/vote/',views.vote,name='vote'),
    path('<int:a>/<int:b>/<int:c>/raizes/',views.raizes,name='raizes'),
]

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date= models.DateTimeField('data published')
    def __str__(self):
        return self.question_text
    #melhorando a interface com @admin
    @admin.display(
        ordering='pub_date',
        boolean=True,
        description='Published recently?',
    )
    def was_published_recently(self):
        now=timezone.now()
        return now-datetime.timedelta(days=1) <=self.pub_date<=now
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from polls.utills import selectChoice
from .models import Choice, Question
from django.views import generic
from django.utils import timezone
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        #retorna os últimos 5 resultados publicados
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
class DetailView(generic.DetailView):
    model=Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Exclupi qualquer questão que não foi publicada ainda.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())
class ResultsView(generic.DetailView):
    model=Question
    template_name='polls/results.html'
def vote(request, question_id):
    question=get_object_or_404(Question,pk=question_id)
    return selectChoice(request,question)
def raizes(request,a,b,c):
    a,b,c=float(a),float(b),float(c)
    x1=(-b+((b*b-4*a*c)**0.5))/2*a
    x2=(-b-((b*b-4*a*c)**0.5))/2*a
    return HttpResponse("O resultado da equação ({})x^2+({})x+({}) são ({},{})".format(a,b,c,x1,x2))

mysite/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend>
        <h1>
            {{ question.question_text }}
        </h1>
    </legend>
    {% if error_message %}
        <p>
            <strong>
                {{ error_message }}
            </strong>
        </p>
    {% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<title>Enquete Questões</title>
		<meta charser="UTF-8">
		<meta name="description".content="Enquete feita com django!">>
    </head>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
{% if latest_question_list%}
    <ul>
        {% for question in latest_question_list %}
            <li>
                <a 
                    href="{% url 'polls:detail' question.id %}">{{ question.question_text }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>
        Nada para ver aqui.
    </p>
{% endif %}
</html>

mysite/polls/templates/polls/results.html
<h1>
    {{question.question_text}}
</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>
            {{ choice.choice_text }}--{{ choice.votes }}vote{{ choice.votes|pluralize }}
        </li>
    {% endfor %}
</ul>

<a 
    href="{% url 'polls:detail' question.id %}">Vote again?
</a>